### ISSUE TITLE
Vertaispalaute välipalautukseen 2

### ISSUE THREAD

**Issue by suomalainenmari** [ilkkamaksy/space-booker#1]
Sovelluksen koodin tai tietokannan puolesta kehitysehdotuksia ei ole, rakenne vaikuttaa hyvältä. Selkeästi eroteltu eri toiminnallisuuksia toteuttavat osat eri tiedostoihin, sekä puurakenne (frontend/backend) ohjaa hyvin ja kiitokset selkeästä readme:stä, pitänee ottaa oppia näistä!

Herokussa tekemiä huomioita, joita voi pohtia:

- Samannimisen organisaation voi luoda
- Organisaation samalla websitella voi luoda
- Tyhjää organisaatiota ei voi tallentaa, mutta website ja description kentän voi jättää tyhjäksi. En tiedä oliko tämä tarkoitus?
- Kun organisaatio tallennettu, olisi jokin palaa etusivulle tai redirectaus hyvä, nyt käyttäjänä cancel-napista paluu mietityttää, että onko organisaatio nyt tallentunut vai ei. Tämä toki selviää dashboardilla, että luotu organisaatio löytyy.

Mutta kaiken kaikkiaan space-bookersin värimaailma on miellyttävä, ja pidin siitä, että palaute ("Väärä tunnus tai salasana") tulee ilman uudelleenohjausta. Hienoa työtä, seuraavaa versiota odotellessa..!

**Comment by ilkkamaksy** [comment]
Kiitos palautteesta!
