### ISSUE TITLE
Vertaispalaute välipalautukseen #3

### ISSUE THREAD

**Issue by osekeranen** [ilkkamaksy/space-booker#2]
Koodin puolesta ei yleisiä parannusehdotuksia, hyvin jäsennelty eri toiminnallisuudet erilleen. En kuitenkaan löytänyt lainkaan kuvausta tietokannasta enkä yhtäkään tiedostoa, jonka avulla olisin pystynyt selventämään sen rakenteen. Kuitenkin ainakin käyttäjien tallentaminen onnistui hyvin. Tässä muutamia huomioita ja parannusehdotuksia

* Organisaatioiden tallentamisen jälkeen voisi uudelleenohjata käyttäjän etusivulle.
* Organisaatiot näyttävät poistuvan kun kirjautuu ulos ja kirjautuu takaisin sisään.
* Servicejen tallentaminen ei onnistunut testikäyttäjällä, eikä itseluodulla käyttäjä ja virheilmoituksesta ("Something went wrong. Please try again.") ei saanut selville miksei.
* Yllä mainitun kohdan takia kalenterin testaaminen oli mahdotonta.
* Lisäksi salasanojen vaatimukset eivät ole käyttäjälle mieluisia ja ne johtavat käyttäjille vaikeasti muistettaviin mutta tietokoneelle helposti murrettaviin salasanoihin. Esimerkiksi [tässä](https://www.youtube.com/watch?v=3NjQ9b3pgIg) on hyvä video aiheesta.

Muuten varsin mainio sovellus, hienoa työtä!

**Comment by ilkkamaksy** [comment]
Kiitos @osekeranen palautteesta!
